# Generated by Django 5.2.5 on 2025-08-31 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_project_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Task name')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=15, verbose_name='Status')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked By Manager')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted by Customer')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('masters', models.ManyToManyField(limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL, verbose_name='Master')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='project.project', verbose_name='project')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('file', models.FileField(blank=True, null=True, upload_to='TaskCommentFiles/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskComment', to='tasks.task', verbose_name='task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskCommentUser', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFilesDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='taskFilesDone/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskFilesDone', to='tasks.task', verbose_name='task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFilesToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='taskFilesToDo/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskFilesToDo', to='tasks.task', verbose_name='task')),
            ],
        ),
    ]
