# Generated by Django 5.2.5 on 2025-08-31 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='taskfilesdone',
            options={'verbose_name_plural': 'Done Files'},
        ),
        migrations.AlterModelOptions(
            name='taskfilestodo',
            options={'verbose_name_plural': 'To Do Files'},
        ),
        migrations.AddField(
            model_name='taskfilesdone',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='taskFilesDoneUser', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
