# Generated by Django 5.2.5 on 2025-08-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
    ]
